# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-05 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classattended', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('group_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='createPerson',
            fields=[
                ('person_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='faces',
            fields=[
                ('face_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=200)),
                ('student_usn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sem', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('sem', models.IntegerField()),
                ('classdone', models.IntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Department')),
            ],
        ),
        migrations.AddField(
            model_name='faces',
            name='Student_usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Student'),
        ),
        migrations.AddField(
            model_name='createperson',
            name='Student_usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='dept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Department'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student_usn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Student'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseapp.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendence',
            unique_together=set([('student_usn', 'subject_id')]),
        ),
    ]
