# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createperson',
            old_name='Student_usn',
            new_name='student_usn',
        ),
        migrations.RenameField(
            model_name='faces',
            old_name='Student_usn',
            new_name='student_usn',
        ),
    ]
